### PR TITLE
Added custom create TOTP device API (In command line, just for admin).

### PR DESCRIPTION
**Pull request by EvanLuo42**

### CODE REVIEW

**Comment by psagers** [comment]
Hello,

Thanks for the idea; what problem is this solving? The `addstatictoken` command already exists to bootstrap access.

**Comment by EvanLuo42** [comment]
> Hello,
> 
> Thanks for the idea; what problem is this solving? The `addstatictoken` command already exists to bootstrap access.

Oh, is it a command that can create totp device by command line? I haven’t noticed that. Because it is inconvenient to login to admin site to create totp device. If there is such a command or api, just close this pull request, thank you.

**Comment by EvanLuo42** [comment]
> > Hello,
> > Thanks for the idea; what problem is this solving? The `addstatictoken` command already exists to bootstrap access.
> 
> Oh, is it a command that can create totp device by command line? I haven’t noticed that. Because it is inconvenient to login to admin site to create totp device. If there is such a command or api, just close this pull request, thank you.



> Hello,
> 
> Thanks for the idea; what problem is this solving? The `addstatictoken` command already exists to bootstrap access.

I wrote this in my custom ‘createsuperuser’ function. So I can use ‘manage.py createsuperuser’ to print a new account with totp qrcode.

**Comment by psagers** [comment]
https://django-otp-official.readthedocs.io/en/stable/overview.html#addstatictoken

**Pull request closed without merging**
