### PR TITLE
Some EmailDevice improvments

### PR DESCRIPTION
**Pull request by arjan-s**
These are two EmailDevice improvements that I felt didn't belong in my previous pull request:

- Allow setting an alternative email address on the device. This allows projects/users to use a secondary email address for 2FA tokens instead of their main email address. This improves security for projects that (have to) use this plugin a tiny bit.

- Allow setting the email body template from a setting instead of only from a template on disk.

### CODE REVIEW

**Comment by psagers** [comment]
Nice, thanks. I'm also working on adding throttling, since we're taking this device seriously now.

**Comment by psagers** [comment]
I just pushed the throttling along with a bit of test and documentation cleanup. Let me know if you're working on anything else; otherwise, if everything looks good, I can release an update any time.

**Comment by arjan-s** [comment]
Awesome! If you want I can test all changes combined tomorrow and let you know. I don't have anything else in the works at the moment, except maybe see if I'm going to base `django-otp-messagebird` on `SideChannelDevice` as well.

**Comment by psagers** [comment]
Sounds good, thanks.

**Comment by arjan-s** [comment]
You actually undid my change to be able to set the email token template with a string instead of a file (the 2nd change in this pr). Is that intentional?

**Comment by psagers** [comment]
Oh, I totally misunderstood that. Somehow I thought the setting was for the name of the template, not the content. Feel free to change it back, and be sure to update the documentation.

Thanks,
Peter

**Comment by psagers** [comment]
Actually, I'll fix this along with a few more test tweaks.

Thanks,
Peter

**Comment by psagers** [comment]
I renamed this setting to `OTP_EMAIL_BODY_TEMPLATE`, restored it to a raw template, updated the docs, and added test coverage. Let me know if that works for you.

**Comment by arjan-s** [comment]
Looks good to me, thank you!

**Comment by arjan-s** [comment]
And to get back to your earlier mention, yes, a new release containing these changes would be great!

**Comment by psagers** [comment]
0.9.0 is up. Thanks for moving this forward.

**Pull request merged**
