### PR TITLE
Enable configuration of OTP_STEP time for email based OTP

### PR DESCRIPTION
**Pull request by PritamDutt**
This PR enhances django_otp.plugins.otp_email by providing support for a configurable _OTP Step Time_ by introducing OTP_STEP_TIME variable.

### CODE REVIEW

**Comment by PritamDutt** [comment]
Thanks @psagers for your response. 
1. Surely I can change OTP_STEP_TIME with OTP_EMAIL_STEP_TIME to make it more consistent. (my bad i missed it)

2. Though I understand that OTP_EMAIL is a demo case, I had specific requirement to provide OTP over email only, hence I started working on this piece where 30seconds was not enough time for OTP validation.

I would not comment on whether to include or not include the improvements, as that would be completely your call. From my point of view, I did some work, which I wanted to share back to the community.

Thanks,
Pritam

**Comment by psagers** [comment]
Fair enough, thanks. One other thing you should consider is that otp_email has a weakness in that there's nothing to prevent a single code being used more than once. Done properly, this would probably use either HOTP or just randomly generated codes.

If you're really relying on this, it may be wise to write a private plugin. I'd recommend thinking carefully about 1) exactly how long you would like a code to last, and 2) ensuring that as soon as a code is accepted, it is no longer valid. (Hence some of the regret, as this demo glosses over some important best practices.)

**Comment by arjan-s** [comment]
I'm actually interested to see a better implementation of the email plugin, since I also have a specific use case where email is required. I would be happy to help with that. It shouldn't be too much work to implement @psagers suggestions.
@psagers if you do not want to include improvements in the main package, perhaps it would be wise to remove the existing plugin in the next release?

**Comment by psagers** [comment]
One nice addition to the core might be some kind of abstract SideChannelDevice base class. Concrete implementations (for email, sms, etc.) could inherit from this to get all of the token management for free and simply implement delivery.

Such a base class could probably just generate a random token on request, store it on the device object along with an expiration time, and delegate delivery. A proper email device would be a pretty trivial layer on top of that.

**Comment by arjan-s** [comment]
That would be awesome indeed

**Comment by dacotagh** [comment]
Yes, let's add OTP_EMAIL_STEP_TIME env var, please!

We are need it...

**Comment by psagers** [comment]
Resolved by #33.

**Pull request closed without merging**
