### PR TITLE
Add ability to pass extra context when rendering email templates

### PR DESCRIPTION
**Pull request by gingrassia**
It would be really useful to be able to send extra context when building the email, that way we can have our custom email template with more things other than the token

### CODE REVIEW

**Comment by psagers** [comment]
Sounds reasonable, thanks. Just missing a bit of documentation. Updating the docstring for autodoc would be a good start, plus perhaps a mention in the `OTP_EMAIL_BODY_TEMPLATE*` settings.

**Comment by gingrassia** [comment]
> Sounds reasonable, thanks. Just missing a bit of documentation. Updating the docstring for autodoc would be a good start, plus perhaps a mention in the `OTP_EMAIL_BODY_TEMPLATE*` settings.

hi @psagers, I added some docs, but I wasn't able to verify that docs under `generate_challenge` were properly rendered... would you mind trying yourself or telling me how to do it? I did `make html` under `docs` folder and then serve it but this is what I got 
image

**Comment by psagers** [comment]
Version 1.0.6

**Comment by gingrassia** [comment]
thanks @psagers!

**Pull request merged**
